global:
  # How long before a command times out. Accepts a duration string: a sequence
  # of decimal numbers, each with optional fraction and a unit suffix: 1d,
  # 1h30m, 5m, 10s. Valid units are "ms", "s", "m", "h". Defaults to 60s.
  # TODO Allow overriding at the command level
  command_timeout: 60s

gort:
  # Gort will automatically create accounts for new users when set.
  # User accounts created this way will still need to be placed into groups
  # by an administrator in order to be granted any permissions.
  allow_self_registration: true

  # The address to listen on for Gort's REST API. Defaults to ":4000".
  api_address: ":4000"

  # Controls the prefix of URLs generated for the core API. URLs may contain a
  # scheme (either http or https), a host, an optional port (defaulting to 80
  # for http and 443 for https), and an optional path.
  # Defaults to localhost
  api_url_base: https://gort:4000

  # Enables development mode. Currently this only affects log output format.
  # Defaults to false
  development_mode: true

  # If true, allows Gort to respond to commands prefixed with ! instead of only
  # via direct mentions. Defaults to true.
  enable_spoken_commands: true

  # If set along with tls_key_file, TLS will be used for API connections.
  # This parameter specifies the path to a certificate file.
  # tls_cert_file: host.crt

  # If set along with tls_cert_file, TLS will be used for API connections.
  # This parameter specifies the path to a key file.
  # The key must not be encrypted with a password.
  # tls_key_file: host.key

database:
  # The host where Gort's PostgreSQL database lives. Defaults to localhost.
  host: postgres

  # The port at which Gort may access its PostgreSQL database. Defaults to 5432.
  port: 5432

  # The user to connect to Gort's PostgreSQL database.
  user: gort

  # The password for connecting to Gort's PostgreSQL database. Alternatively,
  # this value can (and should) be specified via the GORT_DB_PASSWORD envvar.
  password: veryKleverPassw0rd!

  # Set this to true to have Gort connect to its database using SSL.
  # Defaults to false.
  ssl_enabled: true

  # The maximum amount of time a connection may be idle. Expired connections
  # may be closed lazily before reuse. If <= 0, connections are not closed due
  # to a connection's idle time. Defaults to 1m.
  connection_max_idle_time: 0s

  # The maximum amount of time a connection may be reused. Expired connections
  # may be closed lazily before reuse. If <= 0, connections are not closed due
  # to a connection's age. Defaults to 10m
  connection_max_life_time: 0s

  # Sets the maximum number of connections in the idle connection pool. If
  # max_open_connections is > 0 but < max_idle_connections, then this value
  # will be reduced to match max_open_connections.
  # If n <= 0, no idle connections are retained.
  # Defaults to 2
  max_idle_connections: 2

  # The maximum number of open connections to the database. If
  # max_idle_connections is > 0 and the new this is less than
  # max_idle_connections, then max_idle_connections will be reduced to match
  # this value. If n <= 0, then there is no limit on the number of open
  # connections. The default is 0 (unlimited).
  max_open_connections: 0

  # How long to wait for execution of a database query to complete.
  # Defaults to 15s.
  query_timeout: 15s

# Configures Gort's Docker host data. At the moment it only includes two
# values (which are likely to move into a relay configuration, when
# that becomes a thing).
docker:
  # Defines the location of the Docker port. Required.
  host: unix:///var/run/docker.sock

  # The name of a Docker network. If set, any worker containers will be
  # attached to this network. This can be used to allow workers to communicate
  # with a containerized Gort controller.
  network: gort_gort

kubernetes:
  # The selectors for Gort's endpoint resource. Used to dynamically find the
  # API endpoint. If both are omitted the label selector "app=gort" is used.
  endpoint_label_selector: "app=gort,release=gort"
  endpoint_field_selector:

  # The selectors for Gort's pod resource. Used to dynamically find the
  # API endpoint. If both are omitted the label selector "app=gort" is used.
  pod_field_selector: "app=gort,release=gort"
  pod_label_selector:

# List of Discord adapters. Delete this section if not using Discord.
discord:
- # An arbitrary name for human labelling purposes.
  name: MyDiscord

  # The name of the bot, as it appears in Discord. Defaults to the name used
  # when the bot was added to the account.
  bot_name: Gort

  # Bot User OAuth Access Token
  bot_token: INSERT BOT TOKEN HERE

# List of Slack adapters. Delete this section if not using Slack.
slack:
- # An arbitrary name for human labelling purposes.
  name: MySlack

  # App Level Token (https://api.slack.com/authentication/token-types#app)
  # used to connect to Slack. You want the one that starts with "xapp".
  app_token: INSERT APP TOKEN HERE

  # Bot User OAuth Access Token (https://api.slack.com/docs/token-types#bot)
  # used to connect to Slack. You want the one that starts with "xoxb".
  bot_token: INSERT BOT TOKEN HERE

jaeger:
  # The URL for the Jaeger collector that spans are sent to. If not set then
  # no exporter will be created.
  endpoint: http://jaeger:14268/api/traces

  # The username to be used in the authorization header sent for all requests
  # to the collector. If not set no username will be passed.
  username: gort

  # The password to be used in the authorization header sent for all requests
  # to the collector.
  password: veryKleverPassw0rd!
