apiVersion: v2
name: gort
description: ChatOps automation framework
version: 0.0.1
home: https://guide.getgort.io/
appVersion: 0.9.0-dev.0
keywords:
- gort
- chatops
sources:
- https://github.com/getgort/gort
- https://guide.getgort.io/
