/*
 * Copyright 2021 The Gort Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package command

import (
	"fmt"

	"github.com/getgort/gort/types"
)

// Command represents a command typed in by a user. It is typically
// generated by the Parse function.
type Command struct {
	Executable string
	Options    map[string]CommandOption
	Parameters []string
}

// CommandOption represents a command option or flag, and its string
// value (if any).
type CommandOption struct {
	Name  string
	Value types.Value
}

// Parse accepts a slice of token strings and constructs a Command value.
// Its behavior may be modified by passing one or more ParseOptions.
func Parse(tokens []string, options ...ParseOption) (Command, error) {
	po := &parseOptions{false, false, map[string]string{}, map[string]bool{}}
	for _, o := range options {
		o(po)
	}

	if len(tokens) == 0 {
		return Command{}, fmt.Errorf("empty tokens list")
	}

	cmd := Command{
		Executable: tokens[0],
		Options:    map[string]CommandOption{},
		Parameters: []string{},
	}

	tokens = tokens[1:]

	var lastOption *CommandOption = nil

	for i, t := range tokens {
		// Double slash indicates the end of options
		if t == "--" {
			cmd.Parameters = tokens[i+1:]
			break
		}

		// Format: --option
		if len(t) >= 2 && dashCount(t) == 2 {
			lastOption = buildOption(t[2:], po)
			cmd.Options[lastOption.Name] = *lastOption
			continue
		}

		// Format: -I or -Ik
		if len(t) >= 1 && dashCount(t) == 1 {
			if po.agnosticDashes {
				lastOption = buildOption(t[1:], po)
				cmd.Options[lastOption.Name] = *lastOption
			} else {
				for _, ch := range t[1:] {
					lastOption = buildOption(string(ch), po)
					cmd.Options[lastOption.Name] = *lastOption
				}
			}

			continue
		}

		// If we got here, the token isn't an option.

		// Was the previous token an option?
		if lastOption != nil {
			// Does it expect an argument?
			explicitHas, ok := po.hasArg[lastOption.Name]
			hasArgument := (ok && explicitHas) || (!ok && po.assumeOptionArguments)

			// Expect an option:
			if hasArgument {
				value, err := types.GuessTypedValue(t, false)
				if err != nil {
					return cmd, err
				}

				lastOption.Value = value
				cmd.Options[lastOption.Name] = *lastOption
				lastOption = nil
				continue
			}
		}

		// Not an option; not an argument. Must be command args.
		cmd.Parameters = tokens[i:]
		break
	}

	return cmd, nil
}

type parseOptions struct {
	agnosticDashes        bool
	assumeOptionArguments bool
	aliases               map[string]string
	hasArg                map[string]bool
}

type ParseOption func(*parseOptions)

// ParseAgnosticDashes modifies how dashes are interpreted. If true, double and
// single dashes are treated the same. If false (default), then double-dashed
//options are "long" and single-dashed options are "short".
func ParseAgnosticDashes(agnostic bool) ParseOption {
	return func(po *parseOptions) {
		po.agnosticDashes = agnostic
	}
}

// ParseAssumeOptionArguments changes the assumption about whether an option
// not specified using ParseOptionHasArgument should be treated as having an
// option. If false (default), unknown options are assumed to have no argument.
func ParseAssumeOptionArguments(assume bool) ParseOption {
	return func(po *parseOptions) {
		po.assumeOptionArguments = assume
	}
}

// ParseOptionHasArgument allows specific options to be specified as expecting
// an option (or not). Options not specified are treated according to
// ParseAssumeOptionArguments.
func ParseOptionHasArgument(option string, hasArg bool) ParseOption {
	return func(po *parseOptions) {
		po.hasArg[option] = hasArg
	}
}

// ParseOptionAlias allows option aliases to be set, most often "short options"
// to "long options". All references to "alias" are treated as "name".
func ParseOptionAlias(alias, name string) ParseOption {
	return func(po *parseOptions) {
		po.aliases[alias] = name
	}
}

func buildOption(name string, po *parseOptions) *CommandOption {
	if n, ok := po.aliases[name]; ok {
		name = n
	}

	return &CommandOption{Name: name, Value: types.BoolValue{Value: true}}
}

func dashCount(str string) int {
	count := 0

	for _, ch := range str {
		if ch != '-' {
			break
		}

		count++
	}

	return count
}
