apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gort
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gort
            port:
              number: 4000
