apiVersion: v1
kind: Service
metadata:
  name: {{ template "gort.fullname" . }}
  labels:
    app: {{ template "gort.name" . }}
    chart: {{ template "gort.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.gort.service.type }}
  selector:
    app: {{ template "gort.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.gort.externalPort }}
      targetPort: {{ .Values.gort.internalPort }}
      protocol: TCP
      name: {{ .Release.Name }}
